KNOWN_API_METHODS = {
                     "activity" : (
                                   "happenedToUser",
                                   "userDid",
                                   ),
                     "albums" : (
                                 "addVideo",
                                 "create",
                                 "delete",
                                 "getAll",
                                 "getVideos",
                                 "removeVideo",
                                 "setDescription",
                                 "setPassword",
                                 "setTitle",
                                 ),
                     "auth" : (
                              ),
                     "channels" : (
                                   "addVideo",
                                   "getAll",
                                   "getInfo",
                                   "getModerated",
                                   "getModerators",
                                   "getSubscribers",
                                   "getVideos",
                                   "removeVideo",
                                   "subscribe",
                                   "unsubscribe",
                                   ),
                     "contacts" : (
                                   "getAll",
                                   "getMutual",
                                   "getOnline",
                                   "getWhoAdded",
                                   ),
                     "groups" : (
                                 "addVideo",
                                 "getAddable",
                                 "getAll",
                                 "getFiles",
                                 "getInfo",
                                 "getMembers",
                                 "getModerators",
                                 "getVideoComments",
                                 "getVideos",
                                 "join",
                                 "leave",
                                ),
                     "groups_events" : (
                                        "getMonth",
                                        "getPast",
                                        "getUpcoming",
                                       ),
                     "groups_forums" : (
                                        "getTopicComments",
                                        "getTopics",
                                       ),
                     "oauth" : (
                                "checkAccessToken",
                                "convertAuthToken",
                               ),
                     "people" : (
                                 "addContact",
                                 "addSubscription",
                                 "findByEmail",
                                 "getInfo",
                                 "getPortraitUrls",
                                 "getSubscriptions",
                                 "removeContact",
                                 "removeSubscription",
                                ),
                     "test" : (
                               "echo",
                               "login",
                               "null",
                              ),
                     "videos" : (
                                 "addCast",
                                 "addPhotos",
                                 "addTags",
                                 "clearTags",
                                 "delete",
                                 "getAll",
                                 "getAppearsIn",
                                 "getByTag",
                                 "getCast",
                                 "getContactsLiked",
                                 "getContactsUploaded",
                                 "getInfo",
                                 "getLikes",
                                 "getSubscriptions",
                                 "getThumbnailUrls",
                                 "getUploaded",
                                 "removeCast",
                                 "removeTag",
                                 "search",
                                 "setDescription",
                                 "setLike",
                                 "setPrivacy",
                                 "setTitle",
                                ),
                     "videos_comments" : (
                                          "addComment",
                                          "deleteComment",
                                          "editComment",
                                          "getList",
                                         ),
                     "videos_embed" : (
                                       "getPresets",
                                       "setPreset",
                                      ),
                     "videos_upload" : (
                                        "checkTicket",
                                        "complete",
                                        "getQuota",
                                        "getTicket",
                                        "verifyChunks",
                                       ),
}
