# -*- coding: utf-8 -*-
# This file is automatically generated by pypo.py.
# Do not edit; your changes will be erased.

# "NPO Gemist"
npo_gemist = 30000

# "Settings"
settings = 30001

# "Subtitles"
subtitles = 30002

# "Guide"
guide = 30003

# "The television guide for the last week. This includes programs that can not (yet) be played; they will show in italic letters."
the_television_guide_for_the_last_week_ = 30004

# "New"
new = 30005

# "New broadcasts from the last few days."
new_broadcasts_from_the_last_few_days = 30006

# "Today"
today = 30007

# "Yesterday"
yesterday = 30008

# "Day before yesterday"
day_before_yesterday = 30009

# "Programs"
programs = 30010

# "Programs by alphabet."
programs_by_alphabet = 30011

# "Programs starting with the letter {0}."
programs_starting_with_the_letter_I0I = 30012

# "Programs not starting with a letter."
programs_not_starting_with_a_letter = 30013

# "Genres"
genres = 30014

# "Programs by genre."
programs_by_genre = 30015

# "Search for broadcasts by name or description."
search_for_broadcasts_by_name_or_description = 30016

# "Broadcasts of a certain duration. Check here if you want to watch television for a certain time."
broadcasts_of_a_certain_duration_check_here_ = 30017

# "{0}-{1} minutes"
I0II1I_minutes = 30018

# "{0} minutes or more"
I0I_minutes_or_more = 30019

# "re-run"
rerun = 30020

# "All"
all = 30021

# "Broadcasts from all channels"
broadcasts_from_all_channels = 30022

# "New search"
new_search = 30023

# "Earlier search: '{0}'"
earlier_search_I0I = 30024

# "Recently viewed"
recently_viewed = 30025

# "Programs you have recently viewed. Check here if there are new episodes waiting."
programs_you_have_recently_viewed_check_here_ = 30026

# "This program is not available."
this_program_is_not_available = 30027
