# -*- coding: utf-8 -*-
# This file is automatically generated by pypo.py.
# Do not edit; your changes will be erased.

# import * is done deliberately here, to insert all symbols into strings.
# The user of this class shouldn't care from which .po file a string comes.
from .kodi_strings import *
from .local_strings import *
