#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
The standalone updater application module

Copyright (c) 2017-2018, Leo Moll

SPDX-License-Identifier: MIT
"""

# -- Imports ------------------------------------------------
from __future__ import unicode_literals
from resources.lib.mvupdate import UpdateApp

# -- Main Code ----------------------------------------------
if __name__ == '__main__':
    APP = UpdateApp()
    APP.init()
    APP.run()
    APP.exit()
    del APP
