# -*- coding: utf-8 -*-

filter_list = [
    '(acoustic)',
    '(akustik)',
    'unplugged',
    'instrumental',
    'ampya',
    'seltensogelacht',
    'gameplay',
    '(full album stream)',
    #'(behind the video)',
    'behind the',
    #'(behind the scenes)',
    'bts',
    '(making.*?of)',
    'm/v making',
    'making.*?photoshoot',
    'making the video',
    'making video',
    'making film',
    'album photoshoot',
    'documentary',
    'album commentary',
    'track commentary',
    'video commentary',
    'commentary\)',
    'rockumentary',
    '\(official lesson\)',
    'episode\s*\d+',
    'webisode\s*\d+',
    '\#\s*\d+',
    'part\s*\d+',
    'teil\s*\d+',
    'beyond the video',
    'live @',
    'live at',
    'live in session',
    'live from ',
    'live performance',
    'live.*?\d+',
    'live.*?show',
    '\(\w*\s*live in .*?\)',
    '- live in ',
    'o2 arena',
    '(\(|\[)live on.+?(\)|\])',
    '(\(|\[).+?\d{4}(\)|\])',
    'aol session',
    '\d+(/|.)\d+(/|.)\d+',
    '.+?#\w*',
    'download festival',
    'living the dream foundation',
    #'tour diary',
    #'(from .+? tour)',
    'tour',
    'concert',
    'konzert',
    'studio update',
    'in the studio',
    'in studio series',
    'pre production',
    'writing diary',
    'studio diary',
    'studio\s*blog',
    'video\s*blog',
    'album teas',
    'album sample',
    'album\s*player',
    'album spoiler',
    ' digest$',
    'digest(\)|\])',
    'from the road',
    'on the road',
    'teaser',
    '\: the band',
    '\: the dream begins',
    'interview',
    'trailer',
    'the story of',
    'album release video',
    'an intimate performance',
    'performance \d+',
    'promo',
    'ep taster',
    'epk',
    'track\s*by\s*track',
    'sneak peek|peak',
    'log series',
    'intervista',
    'webclip',
    'bundle commercial',
    '(\(|\[)commercial(\)|\])',
    'creature fashion show',
    'auf deutsch',
    '(\[|\s*|\()sub \w+',
    'letra \w+',
    'untertitel',
    'minimix',
    'album release',
    'full.+?album',
    'full.+?ep',
    '\(song\)',
    'new\s*song',
    'full\s*song',
    '\[new\]',
    '(\(|\[).*?(audio|lyric)(\)|\])',
    'official audio',
    'audio only',
    'audio snippet',
    'audio video',
    'track video',
    'track\s*\d+',
    'official\s*track',
    'video\s*\d+(?!.*\w)',
    '\(.*?stream\)',
    'dsds',
    'new album',
    'in stores now',
    'pre(-||\s*)listening',
    'karaoke',
    'a cappella',
    'a capella',
    'live.*?unsigned',
    'dj(-|\s)mix',
    'dj(-|\s)set',
    'live(-|\s)set',
    '(\w+\s+\d{2+})',
    'ask:reply',
    'girl meets world',
    'stars dance',
    '(\d+ (day|days) to go)',
    '(signings)',
    'bring me to.*?:',
    'vault \d+',
    'videodays',
    'shoutout.*?festival',
    'one day (at|@).*?\d+',
    '\w+ records',
    '(parodie)',
    '(parody)',
    '\(.*?cover.*?\)',
    'inglés',
    'español',
    'legendado',
    'tribute to',
    'guitar lesson',
    'un(-||\s)official',
    'officially official',
    '\(outtakes\)',
    '(drum||guitar)(-||\s*)play(-||\s*)through',
    '(album|official)(-||\s*)preview',
    'gmv',
    'q&a:',
    'music video official release',
    'subtitles',
    'announcement',
    'video.*?reaction',
    ]