PATH_ROOT = "/"
PATH_CHARTS = "/charts/"
PATH_DISCOVER = "/discover/"
PATH_PLAY = "/play/"
PATH_SEARCH = "/search/"
PATH_SEARCH_LEGACY = "/search/query/"
PATH_SETTINGS_CACHE_CLEAR = "/settings/cache/clear/"
PATH_USER = "/user/"
