

arts = {
    'All About Android': 'http://twit.cachefly.net/coverart/aaa/aaa1400.jpg',
    'Android App Arena': 'http://twit.cachefly.net/coverart/arena/arena1400.jpg',
    'Before You Buy': 'http://twit.cachefly.net/coverart/byb/byb1400.jpg',
    'Coding 101': 'http://twit.cachefly.net/coverart/code/code1400.jpg',
    'FLOSS Weekly': 'http://twit.cachefly.net/coverart/floss/floss1400.jpg',
    'The Giz Wiz': 'http://twit.cachefly.net/coverart/hn/hn1400.jpg',
    'Ham Nation': 'http://twit.cachefly.net/coverart/hn/hn1400.jpg',
    'Home Theater Geeks': 'http://twit.cachefly.net/coverart/htg/htg1400.jpg',
    'iFive for the iPhone': 'http://twit.cachefly.net/coverart/ifive/ifive1400.jpg',
    'iOS Today': 'http://twit.cachefly.net/coverart/ipad/ipad2048.jpg',
    'iPad Today': 'http://twit.cachefly.net/coverart/ipad/ipad1400.jpg',
    'Know How...': 'http://twit.cachefly.net/coverart/kh/kh1400.jpg',
    'MacBreak Weekly': 'http://twit.cachefly.net/coverart/mbw/mbw1400.jpg',
    'Marketing Mavericks': 'http://twit.cachefly.net/coverart/mm/mm1400.jpg',
    'The New Screen Savers': 'http://twit.cachefly.net/coverart/tnss/tnss2048.jpg',
    "Padre's Corner": 'http://twit.cachefly.net/coverart/padre/padre1400.jpg',
    'Security Now': 'http://twit.cachefly.net/coverart/sn/sn1400.jpg',
    'The Tech Guy': 'http://twit.cachefly.net/coverart/ttg/ttg1400.jpg',
    'Tech News Today': 'http://twit.cachefly.net/coverart/tnt/tnt1400.jpg',
    'Tech News 2Night': 'http://twit.cachefly.net/coverart/tn2n/tn2n1400.jpg',
    'This Week in Computer Hardware': 'http://twit.cachefly.net/coverart/twich/twich1400.jpg',
    'This Week in Enterprise Tech': 'http://twit.cachefly.net/coverart/twiet/twiet1400.jpg',
    'This Week in Google': 'http://twit.cachefly.net/coverart/twig/twig1400.jpg',
    'This Week in Law': 'http://twit.cachefly.net/coverart/twil/twil1400.jpg',
    'This Week in Tech': 'http://twit.cachefly.net/coverart/twit/twit1400.jpg',
    'Triangulation': 'http://twit.cachefly.net/coverart/tri/tri1400.jpg',
    'TWiT Live Specials': 'http://twit.cachefly.net/coverart/specials/specials1400.jpg',
    'Windows Weekly': 'http://twit.cachefly.net/coverart/ww/ww1400.jpg',
    'All TWiT Shows': 'http://twit.cachefly.net/coverart/all/all1400.jpg',
    'Radio Leo': 'http://twit.cachefly.net/coverart/radioleo/radioleo1400.jpg',
    'TWiT Bits': 'http://twit.cachefly.net/coverart/bits/bits1400.jpg',
    "Abby's Road": 'http://twit.cachefly.net/coverart/abby/abby600.jpg',
    'FourCast': 'http://twit.cachefly.net/coverart/fc/fc600.jpg',
    'Futures in Biotech': 'http://twit.cachefly.net/coverart/fib/fib600.jpg',
    'Game On!': 'http://twit.cachefly.net/coverart/go/go600.jpg',
    'Green Tech Today': 'http://twit.cachefly.net/coverart/gtt/gtt600.jpg',
    'Jumping Monkeys': 'http://twit.cachefly.net/coverart/jm/jm300.jpg',
    'The Laporte Report': 'http://twit.cachefly.net/coverart/tlr/tlr300.jpg',
    "Maxwell's House": 'http://twit.cachefly.net/coverart/mh/mh600.jpg',
    'Munchcast': 'http://twit.cachefly.net/coverart/mc/mc300.jpg',
    'OMGcraft': 'http://twit.cachefly.net/coverart/omgcraft/omgcraft1400.jpg',
    'redditUP': 'http://twit.cachefly.net/coverart/ru/ru1400.jpg',
    "Dr. Kiki's Science Hour": 'http://twit.cachefly.net/coverart/snw/snw600.jpg',
    'The Social Hour': 'http://twit.cachefly.net/coverart/tsh/tsh1400.jpg',
    'this WEEK in FUN': 'http://twit.cachefly.net/coverart/twif/twif600.jpg',
    'This Week in Radio Tech': 'http://twit.cachefly.net/coverart/twirt/twirt600.jpg',
    'This Week in YouTube': 'http://twit.cachefly.net/coverart/yt/yt1400.jpg',
    "Trey's Variety Hour": 'http://twit.cachefly.net/coverart/tvh/tvh600.jpg',
    'TWiT Photo': 'http://twit.cachefly.net/coverart/photo/photo600.jpg',
    'All TWiT.tv Shows': 'http://twit.cachefly.net/coverart/all/all1400.jpg'
    }