# This Python file uses the following encoding: utf-8
retired_shows = [
  {'art': 'http://twit.cachefly.net/coverart/abby/abby600.jpg',
   'desc': 'Abby Laporte and her guests as they offer fresh perspectives on '
           'difficult teen subjects.',
   'feeds': {'MP3': 'http://feeds.twit.tv/abby.xml'},
   'title': "Abby's Road",
   'url': '/shows/abbys-road'},
  {'art': 'http://twit.cachefly.net/coverart/arena/arena1400.jpg',
   'desc': "This week's top Android apps",
   'feeds': {'MP3': 'http://feeds.twit.tv/arena.xml',
             'Video-HD': 'http://feeds.twit.tv/arena_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/arena_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/arena_video_small.xml'},
   'title': 'Android App Arena',
   'url': '/shows/android-app-arena'},
  {'art': 'http://twit.cachefly.net/coverart/byb/byb1400.jpg',
   'desc': "You've got to watch... before you buy! The latest tech put to the "
           'test.',
   'feeds': {'MP3': 'http://feeds.twit.tv/byb.xml',
             'Video-HD': 'http://feeds.twit.tv/byb_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/byb_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/byb_video_small.xml'},
   'title': 'Before You Buy',
   'url': '/shows/before-you-buy'},
  {'art': 'http://twit.cachefly.net/coverart/code/code1400.jpg',
   'desc': 'An introduction to computer programming in many languages.',
   'feeds': {'MP3': 'http://feeds.twit.tv/code.xml',
             'Video-HD': 'http://feeds.twit.tv/code_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/code_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/code_video_small.xml'},
   'title': 'Coding 101',
   'url': '/shows/coding-101'},
  {'art': 'http://twit.cachefly.net/coverart/snw/snw600.jpg',
   'desc': "Dr. Kiki's Science Hour is an in-depth exploration of scientific "
           'topics ranging from climate change to nanotech.',
   'feeds': {'MP3': 'http://feeds.twit.tv/kiki.xml',
             'Video-HI': 'http://feeds.twit.tv/dksh_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/dksh_video_small.xml'},
   'title': "Dr. Kiki's Science Hour",
   'url': '/shows/dr-kikis-science-hour'},
  {'art': 'https://twit.cachefly.net/coverart/fop/fop2048.jpg',
   'desc': 'Candid chats about photography with Ant Pruitt and some of the '
           'industry’s hottest photographers.',
   'feeds': {'MP3': 'https://feeds.twit.tv/fop.xml'},
   'title': 'Focus On Photography',
   'url': '/shows/focus-on-photography'},
  {'art': 'http://twit.cachefly.net/coverart/fc/fc600.jpg',
   'desc': 'Join Scott Johnson and Tom Merritt to get short term, long term, '
           'and crazy predictions.',
   'feeds': {'MP3': 'http://feeds.twit.tv/fc.xml',
             'Video-HI': 'http://feeds.twit.tv/fc_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/fc_video_small.xml'},
   'title': 'FourCast',
   'url': '/shows/fourcast'},
  {'art': 'http://twit.cachefly.net/coverart/fib/fib600.jpg',
   'desc': 'Explore the world of cloning, protein folding, genome mapping, and '
           'more with the most important researchers in the field.',
   'feeds': {'MP3': 'http://feeds.twit.tv/fib.xml',
             'Video-HI': 'http://feeds.twit.tv/fib_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/fib_video_small.xml'},
   'title': 'Futures in Biotech',
   'url': '/shows/futures-in-biotech'},
  {'art': 'http://twit.cachefly.net/coverart/go/go600.jpg',
   'desc': 'Veronica and Brian bring you news, reviews, and commentary about '
           "console and PC games that you'll get nowhere else.",
   'feeds': {'MP3': 'http://feeds.twit.tv/go.xml',
             'Video-HI': 'http://feeds.twit.tv/go_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/go_video_small.xml'},
   'title': 'Game On!',
   'url': '/shows/game-on'},
  {'art': 'http://twit.cachefly.net/coverart/gtt/gtt600.jpg',
   'desc': 'Green Tech Today is the essential show for the eco-minded geek.',
   'feeds': {'MP3': 'http://feeds.twit.tv/gtt.xml',
             'Video-HI': 'http://feeds.twit.tv/gtt_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/gtt_video_small.xml'},
   'title': 'Green Tech Today',
   'url': '/shows/green-tech-today'},
  {'art': 'http://twit.cachefly.net/coverart/htg/htg1400.jpg',
   'desc': 'This is the show for big screen TVs to surround sound to the '
           'latest video tech.',
   'feeds': {'MP3': 'http://feeds.twit.tv/htg.xml',
             'Video-HD': 'http://feeds.twit.tv/htg_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/htg_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/htg_video_small.xml'},
   'title': 'Home Theater Geeks',
   'url': '/shows/home-theater-geeks'},
  {'art': 'http://twit.cachefly.net/coverart/ifive/ifive1400.jpg',
   'desc': 'Five apps, five tips, five minutes all about the iPhone.',
   'feeds': {'MP3': 'http://feeds.twit.tv/ifive.xml',
             'Video-LO': 'http://feeds.twit.tv/ifive_video_small.xml',
             'Video-HI': 'http://feeds.twit.tv/ifive_video_large.xml',
             'Video-HD': 'http://feeds.twit.tv/ifive_video_hd.xml'},
   'title': 'iFive for the iPhone',
   'url': '/shows/ifive-iphone'},
  {'art': 'http://twit.cachefly.net/coverart/jm/jm300.jpg',
   'desc': 'Megan and Leo they talk about parenting in the digital age.',
   'feeds': {'MP3': 'http://feeds.twit.tv/jm.xml'},
   'title': 'Jumping Monkeys',
   'url': '/shows/jumping-monkeys'},
  {'art': 'http://twit.cachefly.net/coverart/kh/kh1400.jpg',
   'desc': 'Learn how to make technology work for you.',
   'feeds': {'MP3': 'http://feeds.twit.tv/kh.xml',
             'Video-HD': 'http://feeds.twit.tv/kh_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/kh_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/kh_video_small.xml'},
   'title': 'Know How...',
   'url': '/shows/know-how'},
  {'art': 'https://twit.cachefly.net/coverart/macbreak/macbreak2048.jpg',
   'desc': 'Mac experts talk about everything Mac.',
   'feeds': {'MP3': 'http://feeds.twit.tv/mbw.xml',
             'Video-LO': 'http://feeds.twit.tv/mbw_video_small.xml',
             'Video-HI': 'http://feeds.twit.tv/mbw_video_large.xml',
             'Video-HD': 'http://feeds.twit.tv/mbw_video_hd.xml'},
   'title': 'MacBreak',
   'url': '/shows/macbreak'},
  {'art': 'http://twit.cachefly.net/coverart/mm/mm1400.jpg',
   'desc': 'Marketing Mavericks covers the intersection of marketing and tech.',
   'feeds': {'MP3': 'http://feeds.twit.tv/mm.xml',
             'Video-HD': 'http://feeds.twit.tv/mm_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/mm_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/mm_video_small.xml'},
   'title': 'Marketing Mavericks',
   'url': '/shows/marketing-mavericks'},
  {'art': 'http://twit.cachefly.net/coverart/mh/mh600.jpg',
   'desc': "Stop by the house of polymath Ray Maxwell and see what he's "
           'investigating today.',
   'feeds': {'MP3': 'http://feeds.twit.tv/mh.xml',
             'Video-HI': 'http://feeds.twit.tv/mh_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/mh_video_small.xml'},
   'title': "Maxwell's House",
   'url': '/shows/maxwells-house'},
  {'art': 'http://twit.cachefly.net/coverart/mc/mc300.jpg',
   'desc': 'Munchcast covers geek food in all its guises.',
   'feeds': {'MP3': 'http://feeds.twit.tv/mc.xml'},
   'title': 'Munchcast',
   'url': '/shows/munchcast'},
  {'art': 'https://twit.cachefly.net/coverart/natn/natn1400.jpg',
   'desc': "What's happening on the 'net right now?",
   'feeds': {'MP3': 'http://feeds.twit.tv/itn.xml',
             'Video-LO': 'http://feeds.twit.tv/natn_video_small.xml',
             'Video-HI': 'http://feeds.twit.tv/natn_video_large.xml'},
   'title': 'net@night',
   'url': '/shows/netnight'},
  {'art': 'http://twit.cachefly.net/coverart/omgcraft/omgcraft1400.jpg',
   'desc': 'Your one-stop-shop for everything Minecraft.',
   'feeds': {'MP3': 'http://feeds.twit.tv/omgcraft.xml',
             'Video-HD': 'http://feeds.twit.tv/omgcraft_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/omgcraft_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/omgcraft_video_small.xml'},
   'title': 'OMGcraft',
   'url': '/shows/omgcraft'},
  {'art': 'http://twit.cachefly.net/coverart/padre/padre1400.jpg',
   'desc': 'Join Padre each week as he picks up the stories that fall through '
           'the cracks.',
   'feeds': {'MP3': 'http://feeds.twit.tv/padre.xml',
             'Video-HD': 'http://feeds.twit.tv/padre_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/padre_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/padre_video_small.xml'},
   'title': "Padre's Corner",
   'url': '/shows/padres-corner'},
  {'art': 'http://twit.cachefly.net/coverart/ru/ru1400.jpg',
   'desc': 'The best that "the front page of the internet" has to offer.',
   'feeds': {'MP3': 'http://feeds.twit.tv/ru.xml',
             'Video-LO': 'http://feeds.twit.tv/ru_video_small.xml',
             'Video-HI': 'http://feeds.twit.tv/ru_video_large.xml',
             'Video-HD': 'http://feeds.twit.tv/ru_video_hd.xml'},
   'title': 'redditUP',
   'url': '/shows/redditup'},
  {'art': 'https://twit.cachefly.net/coverart/roz/roz300.jpg',
   'desc': 'Join Roz Savage as she becomes the first woman to row solo across '
           'the Pacific.',
   'feeds': {'MP3': 'http://feeds.twit.tv/roz.xml'},
   'title': 'Roz Rows the Pacific',
   'url': '/shows/roz-rows-the-pacific'},
  {'art': 'https://twit.cachefly.net/coverart/snw/snw600.jpg',
   'desc': 'Keep up with the most interesting science to make headlines each '
           'week.',
   'feeds': {'MP3': 'http://feeds.twit.tv/snw.xml',
             'Video-HI': 'http://feeds.twit.tv/snw_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/snw_video_small.xml'},
   'title': 'Science News Weekly',
   'url': '/shows/science-news-weekly'},
  {'art': 'http://twit.cachefly.net/coverart/tn2n/tn2n1400.jpg',
   'desc': "Wrap up the day's tech news with Megan Morrone and the best "
           'journalists in tech.',
   'feeds': {'MP3': 'http://feeds.twit.tv/tn2n.xml',
             'Video-HD': 'http://feeds.twit.tv/tn2n_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/tn2n_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/tn2n_video_small.xml'},
   'title': 'Tech News 2Night',
   'url': '/shows/tech-news-2night'},
  {'art': 'http://twit.cachefly.net/coverart/tnt/tnt1400.jpg',
   'desc': 'Your daily dose of tech news featuring the top tech journalists.',
   'feeds': {'MP3': 'http://feeds.twit.tv/tnt.xml',
             'Video-HD': 'http://feeds.twit.tv/tnt_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/tnt_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/tnt_video_small.xml'},
   'title': 'Tech News Today',
   'url': '/shows/tech-news-today'},
  {'art': 'http://twit.cachefly.net/coverart/hn/hn1400.jpg',
   'desc': 'Dick DeBartolo and OMGchad showcase useful, unique, and silly '
           'gadgets and gizmos.',
   'feeds': {'MP3': 'http://gizwiz.tv/feed/audio',
             'Video-LO': 'http://gizwiz.tv/feed/video_low',
             'Video-HI': 'http://gizwiz.tv/feed/video'},
   'title': 'The Giz Wiz',
   'url': '/shows/weekly-daily-giz-wiz'},
  {'art': 'http://twit.cachefly.net/coverart/tlr/tlr300.jpg',
   'desc': 'Miscellaneous audio from TV and radio technology guru Leo Laporte.',
   'feeds': {'MP3': 'http://feeds.twit.tv/tlr.xml'},
   'title': 'The Laporte Report',
   'url': '/shows/the-laporte-report'},
  {'art': 'http://twit.cachefly.net/coverart/tnss/tnss2048.jpg',
   'desc': 'The New Screen Savers is a variety show for tech on the TWiT '
           'network.',
   'feeds': {'MP3': 'http://feeds.twit.tv/tnss.xml',
             'Video-HD': 'http://feeds.twit.tv/tnss_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/tnss_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/tnss_video_small.xml'},
   'title': 'The New Screen Savers',
   'url': '/shows/new-screen-savers'},
  {'art': 'http://twit.cachefly.net/coverart/tsh/tsh1400.jpg',
   'desc': 'Your source for the best social tools, news, and fascinating folks '
           'building the next generation of the Internet.',
   'feeds': {'MP3': 'http://feeds.twit.tv/tsh.xml',
             'Video-HD': 'http://feeds.twit.tv/tsh_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/tsh_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/tsh_video_small.xml'},
   'title': 'The Social Hour',
   'url': '/shows/social-hour'},
  {'art': 'http://twit.cachefly.net/coverart/twif/twif600.jpg',
   'desc': "This week's fun facts in an irreverent look at the news.",
   'feeds': {'MP3': 'http://feeds.twit.tv/tsh.xml',
             'Video-LO': 'http://feeds.twit.tv/tsh_video_small.xml',
             'Video-HI': 'http://feeds.twit.tv/tsh_video_large.xml',
             'Video-HD': 'http://feeds.twit.tv/tsh_video_hd.xml'},
   'title': 'this WEEK in FUN',
   'url': '/shows/this-week-in-fun'},
  {'art': 'http://twit.cachefly.net/coverart/twil/twil1400.jpg',
   'desc': 'Join Denise as she discusses issues in technology law.',
   'feeds': {'MP3': 'http://feeds.twit.tv/twil.xml',
             'Video-HD': 'http://feeds.twit.tv/twil_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/twil_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/twil_video_small.xml'},
   'title': 'This Week in Law',
   'url': '/shows/this-week-in-law'},
  {'art': 'http://twit.cachefly.net/coverart/twirt/twirt600.jpg',
   'desc': 'Advice, stories, and instruction from some of the sharpest minds '
           'in audio media tech.',
   'feeds': {'MP3': 'http://feeds.twit.tv/twirt.xml',
             'Video-HI': 'http://feeds.twit.tv/twirt_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/twirt_video_small.xml'},
   'title': 'This Week in Radio Tech',
   'url': '/shows/this-week-in-radio-tech'},
  {'art': 'http://twit.cachefly.net/coverart/yt/yt1400.jpg',
   'desc': 'Lamarr and Chad explore the world of online viral video.',
   'feeds': {'MP3': 'http://feeds.twit.tv/yt.xml',
             'Video-HD': 'http://feeds.twit.tv/yt_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/yt_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/yt_video_small.xml'},
   'title': 'This Week in YouTube',
   'url': '/shows/this-week-in-youtube'},
  {'art': 'http://twit.cachefly.net/coverart/tvh/tvh600.jpg',
   'desc': 'Photography, art, the future, and the nature of the new culture we '
           'are all building together.',
   'feeds': {'MP3': 'http://feeds.twit.tv/tvh.xml',
             'Video-HI': 'http://feeds.twit.tv/tvh_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/tvh_video_small.xml'},
   'title': "Trey's Variety Hour",
   'url': '/shows/treys-variety-hour'},
  {'art': 'http://twit.cachefly.net/coverart/tri/tri1400.jpg',
   'desc': 'The smartest people in the world talking about the most important '
           'topics in technology.',
   'feeds': {'MP3': 'http://feeds.twit.tv/tri.xml',
             'Video-HD': 'http://feeds.twit.tv/tri_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/tri_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/tri_video_small.xml'},
   'title': 'Triangulation',
   'url': '/shows/triangulation'},
  {'art': 'http://twit.cachefly.net/coverart/photo/photo600.jpg',
   'desc': 'Learn tips from pros as they impart their knowledge through '
           'anecdotes, experience, and discussion.',
   'feeds': {'MP3': 'http://feeds.twit.tv/photo.xml',
             'Video-HD': 'http://feeds.twit.tv/photo_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/photo_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/photo_video_small.xml'},
   'title': 'TWiT Photo',
   'url': '/shows/twit-photo'},
  {'art': 'https://twit.cachefly.net/coverart/vog/vog1400.jpg',
   'desc': 'Valley of Genius features the hackers, founders, and freaks who '
           'made Silicon Valley boom, in their own words.',
   'feeds': {'MP3': 'http://feeds.twit.tv/vog.xml'},
   'title': 'Valley of Genius',
   'url': '/shows/valley-of-genius'}]

active_shows = [
  {'art': 'https://twit.cachefly.net/coverart/all/all2048.jpg',
   'desc': 'A feed of all the shows produced by TWiT.tv.',
   'feeds': {'MP3': 'http://feeds.twit.tv/leo.xml',
             'Video-LO': 'http://feeds.twit.tv/leo_video_small.xml',
             'Video-HI': 'http://feeds.twit.tv/leo_video_large.xml',
             'Video-HD': 'http://feeds.twit.tv/leo_video_hd.xml'},
   'title': 'All TWiT.tv Shows',
   'url': '/shows/all-twittv-shows'},
  {'art': 'http://twit.cachefly.net/coverart/twit/twit1400.jpg',
   'desc': 'Your first podcast of the week is the last word in tech.',
   'feeds': {'MP3': 'http://feeds.twit.tv/twit.xml',
             'Video-HD': 'http://feeds.twit.tv/twit_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/twit_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/twit_video_small.xml'},
   'title': 'This Week in Tech',
   'url': '/shows/this-week-in-tech'},
  {'art': 'http://twit.cachefly.net/coverart/sn/sn1400.jpg',
   'desc': 'Steve Gibson discusses the hot topics in security today with Leo '
           'Laporte.',
   'feeds': {'MP3': 'http://feeds.twit.tv/sn.xml',
             'Video-HD': 'http://feeds.twit.tv/sn_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/sn_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/sn_video_small.xml'},
   'title': 'Security Now',
   'url': '/shows/security-now'},
  {'art': 'http://twit.cachefly.net/coverart/ttg/ttg1400.jpg',
   'desc': 'Leo Laporte takes to the radio every weekend to talk tech and '
           'answer your questions.',
   'feeds': {'MP3': 'http://feeds.twit.tv/kfi.xml',
             'Video-HD': 'http://feeds.twit.tv/ttg_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/ttg_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/ttg_video_small.xml'},
   'title': 'The Tech Guy',
   'url': '/shows/the-tech-guy'},
  {'art': 'https://twit.cachefly.net/coverart/atg/atg2048.jpg',
   'desc': "Need tech help? Don't fear, don't fret, don't freak out - just Ask "
           'The Tech Guy!',
   'feeds': {'MP3': 'https://feeds.twit.tv/atg.xml',
             'Video-HD': 'https://feeds.twit.tv/atg_video_hd.xml',
             'Video-HI': 'https://feeds.twit.tv/atg_video_large.xml',
             'Video-LO': 'https://feeds.twit.tv/atg_video_small.xml'},
   'title': 'Ask The Tech Guy',
   'url': '/shows/ask-the-tech-guy'},
  {'art': 'http://twit.cachefly.net/coverart/ww/ww1400.jpg',
   'desc': 'Paul Thurrott and Mary Jo Foley talk about Windows and all things '
           'Microsoft.',
   'feeds': {'MP3': 'http://feeds.twit.tv/ww.xml',
             'Video-HD': 'http://feeds.twit.tv/ww_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/ww_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/ww_video_small.xml'},
   'title': 'Windows Weekly',
   'url': '/shows/windows-weekly'},
  {'art': 'http://twit.cachefly.net/coverart/mbw/mbw1400.jpg',
   'desc': 'Get the latest Apple news and views from the top names in tech '
           'journalism.',
   'feeds': {'MP3': 'http://feeds.twit.tv/mbw.xml',
             'Video-HD': 'http://feeds.twit.tv/mbw_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/mbw_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/mbw_video_small.xml'},
   'title': 'MacBreak Weekly',
   'url': '/shows/macbreak-weekly'},
  {'art': 'https://twit.cachefly.net/coverart/stt/stt2048.jpg',
   'desc': 'Be it smart bulbs or smart assistants -- and everything in between '
           '-- Smart Tech Today helps you make the most of...',
   'feeds': {'MP3': 'https://feeds.twit.tv/stt.xml',
             'Video-HD': 'https://feeds.twit.tv/stt_video_hd.xml',
             'Video-HI': 'https://feeds.twit.tv/stt_video_large.xml',
             'Video-LO': 'https://feeds.twit.tv/stt_video_small.xml'},
   'title': 'Smart Tech Today',
   'url': '/shows/smart-tech-today'},
  {'art': 'http://twit.cachefly.net/coverart/twig/twig1400.jpg',
   'desc': 'The latest Google and cloud computing news.',
   'feeds': {'MP3': 'http://feeds.twit.tv/twig.xml',
             'Video-HD': 'http://feeds.twit.tv/twig_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/twig_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/twig_video_small.xml'},
   'title': 'This Week in Google',
   'url': '/shows/this-week-in-google'},
  {'art': 'https://twit.cachefly.net/coverart/hop/hop2048.jpg',
   'desc': 'Create awesome images with your smartphone or camera.',
   'feeds': {'MP3': 'https://feeds.twit.tv/hop.xml',
             'Video-HD': 'https://feeds.twit.tv/hop_video_hd.xml',
             'Video-HI': 'https://feeds.twit.tv/hop_video_large.xml',
             'Video-LO': 'https://feeds.twit.tv/hop_video_small.xml'},
   'title': 'Hands-On Photography',
   'url': '/shows/hands-on-photography'},
  {'art': 'https://twit.cachefly.net/coverart/tnw/tnw2048.jpg',
   'desc': 'Your weekly dose of tech news featuring the top tech journalists.',
   'feeds': {'MP3': 'http://feeds.twit.tv/tnw.xml',
             'Video-HD': 'http://feeds.twit.tv/tnw_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/tnw_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/tnw_video_small.xml'},
   'title': 'Tech News Weekly',
   'url': '/shows/tech-news-weekly'},
  {'art': 'https://twit.cachefly.net/coverart/ipad/ipad2048.jpg',
   'desc': "iPhone, iPad, Apple Watch, or Apple TV... If it's iOS, Leo and "
           "Mikah show you what's new and what's cool.",
   'feeds': {'MP3': 'http://feeds.twit.tv/ipad.xml',
             'Video-LO': 'http://feeds.twit.tv/ipad_video_small.xml',
             'Video-HI': 'http://feeds.twit.tv/ipad_video_large.xml',
             'Video-HD': 'http://feeds.twit.tv/ipad_video_hd.xml'},
   'title': 'iOS Today',
   'url': '/shows/ios-today'},
  {'art': 'http://twit.cachefly.net/coverart/aaa/aaa1400.jpg',
   'desc': 'The Android experts keep you posted on the latest news, hardware '
           'and apps.',
   'feeds': {'MP3': 'http://feeds.twit.tv/aaa.xml',
             'Video-HD': 'http://feeds.twit.tv/aaa_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/aaa_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/aaa_video_small.xml'},
   'title': 'All About Android',
   'url': '/shows/all-about-android'},
  {'art': 'https://twit.cachefly.net/coverart/hot/hot2048.jpg',
   'desc': "Hands-On Tech is where you'll find hands-on reviews, previews, and "
           'unboxings of the hottest tech gadgets.',
   'feeds': {'MP3': 'http://feeds.twit.tv/hot.xml',
             'Video-HD': 'http://feeds.twit.tv/hot_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/hot_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/hot_video_small.xml'},
   'title': 'Hands-On Tech',
   'url': '/shows/hands-on-tech'},
  {'art': 'http://twit.cachefly.net/coverart/twiet/twiet1400.jpg',
   'desc': 'Keep up on the latest in cutting edge enterprise tech.',
   'feeds': {'MP3': 'http://feeds.twit.tv/twiet.xml',
             'Video-HD': 'http://feeds.twit.tv/twiet_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/twiet_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/twiet_video_small.xml'},
   'title': 'This Week in Enterprise Tech',
   'url': '/shows/this-week-in-enterprise-tech'},
  {'art': 'http://twit.cachefly.net/coverart/twich/twich1400.jpg',
   'desc': 'Do you obsess about computer hardware? This is the show for you!',
   'feeds': {'MP3': 'http://feeds.twit.tv/twich.xml',
             'Video-HD': 'http://feeds.twit.tv/twich_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/twich_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/twich_video_small.xml'},
   'title': 'This Week in Computer Hardware',
   'url': '/shows/this-week-in-computer-hardware'},
  {'art': 'http://twit.cachefly.net/coverart/floss/floss1400.jpg',
   'desc': 'We show off free, libre, and open source software here each week.',
   'feeds': {'MP3': 'http://feeds.twit.tv/floss.xml',
             'Video-HD': 'http://feeds.twit.tv/floss_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/floss_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/floss_video_small.xml'},
   'title': 'FLOSS Weekly',
   'url': '/shows/floss-weekly'},
  {'art': 'http://twit.cachefly.net/coverart/hn/hn1400.jpg',
   'desc': 'Calling all hams! The ultimate amateur radio talk show meets here '
           'weekly.',
   'feeds': {'MP3': 'http://feeds.twit.tv/hn.xml',
             'Video-HD': 'http://feeds.twit.tv/hn_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/hn_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/hn_video_small.xml'},
   'title': 'Ham Nation',
   'url': '/shows/ham-nation'},
  {'art': 'https://twit.cachefly.net/coverart/events/events2048.jpg',
   'desc': 'TWiT Events is your window to the best tech events in the world.',
   'feeds': {'MP3': 'http://feeds.twit.tv/events.xml',
             'Video-HD': 'http://feeds.twit.tv/events_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/events_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/events_video_small.xml'},
   'title': 'TWiT Events',
   'url': '/shows/twit-events'},
  {'art': 'https://twit.cachefly.net/coverart/news/news2048.jpg',
   'desc': 'Get the latest product announcements from all the tech giants, '
           'plus breaking tech news as it happens.',
   'feeds': {'MP3': 'http://feeds.twit.tv/ces.xml',
             'Video-HD': 'http://feeds.twit.tv/specials_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/specials_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/specials_video_small.xml'},
   'title': 'TWiT News',
   'url': '/shows/twit-news'},
  {'art': 'http://twit.cachefly.net/coverart/bits/bits1400.jpg',
   'desc': 'Highlights from various shows on TWiT.tv.',
   'feeds': {'MP3': 'http://feeds.twit.tv/bits.xml',
             'Video-HD': 'http://feeds.twit.tv/bits_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/bits_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/bits_video_small.xml'},
   'title': 'TWiT Bits',
   'url': '/shows/twit-bits'},
  {'art': 'http://twit.cachefly.net/coverart/radioleo/radioleo1400.jpg',
   'desc': 'A compendium of podcasts from the Chief TWiT, Leo Laporte.',
   'feeds': {'MP3': 'http://feeds.twit.tv/leo.xml',
             'Video-HD': 'http://feeds.twit.tv/leo_video_hd.xml',
             'Video-HI': 'http://feeds.twit.tv/leo_video_large.xml',
             'Video-LO': 'http://feeds.twit.tv/leo_video_small.xml'},
   'title': 'Radio Leo',
   'url': '/shows/radio-leo'}]

