# -*- encoding: utf-8 -*-
"""
    keys

    string constants
"""

ALLOW_AUDIO_ONLY = 'allow_audio_only'
ALLOW_SOURCE = 'allow_source'
ALLOW_SPECTRE = 'allow_spectre'
AVATAR_IMAGE = 'avatar_image'
BROADCAST_TYPE = 'broadcast_type'
BROADCASTER_LANGUAGE = 'broadcaster_language'
BROADCASTS = 'broadcasts'
CHANNEL = 'channel'
CHANNEL_FEED_ENABLED = 'channel_feed_enabled'
CHANNEL_ID = 'channel_id'
CLIP = 'clip'
COLLECTION_ID = 'collection_id'
COMMENT_ID = 'comment_id'
COMMENTS = 'comments'
COMMUNITIES = 'communities'
COMMUNITY_ID = 'community_id'
CONTAINING_ITEM = 'containing_item'
CONTENT = 'content'
COVER_IMAGE = 'cover_image'
CURSOR = 'cursor'
CLIENT_ID = 'client_id'
DELAY = 'delay'
DESCRIPTION = 'description'
DIRECTION = 'direction'
DURATION = 'duration'
EMAIL = 'email'
EMOTE_ID = 'emote_id'
EMOTESETS = 'emotesets'
ERROR = 'error'
FEATURED = 'featured'
FOLLOWS = 'follows'
GAME = 'game'
HLS = 'hls'
ID = 'id'
IDENTIFIER = 'identifier'
INCLUDE_ALL_ITEMS = 'include_all_items'
ITEM_ID = 'item_id'
LANGUAGE = 'language'
LIMIT = 'limit'
LIVE = 'live'
MESSAGE = 'message'
NAME = 'name'
NAUTH = 'nauth'
NAUTHSIG = 'nauthsig'
NEED_HTTPS = 'need_https'
NOTIFICATIONS = 'notifications'
OFFSET = 'offset'
PART = 'part'
PERIOD = 'period'
POSITION = 'position'
POST_ID = 'post_id'
QUERY = 'query'
REASON = 'reason'
RULES = 'rules'
SCE_PLATFORM = 'sce_platform'
SHARE = 'share'
SIG = 'sig'
SLUG = 'slug'
SORT = 'sort'
SORT_BY = 'sortby'
STATUS = 'status'
STREAM_TYPE = 'stream_type'
SUMMARY = 'summary'
TAG_LIST = 'tag_list'
TARGET_ID = 'target_id'
TEAM = 'team'
TITLE = 'title'
TOKEN = 'token'
TRENDING = 'trending'
TYPE = 'type'
USER = 'user'
USERNAME = 'username'
USER_AGENT = 'User-Agent'
USER_AGENT_STRING = ('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:6.0) '
                     'Gecko/20100101 Firefox/6.0')
USER_ID = 'user_id'
UPLOAD_TOKEN = 'upload_token'
VIDEO_ID = 'video_id'
VOD = 'vod'
XBOX_HEARTBEAT = 'xbox_heartbeat'
