URLTED = 'http://www.ted.com'
URLPROFILES = URLTED + '/profiles'
URLFAVORITES = URLPROFILES + '/favorites/id/'
URLADDREMFAV = URLPROFILES + '/%sfavorites'
URLSPEAKERS = URLTED + '/speakers?orderedby=TALKPOSTED&page=%s&alphabylastname=%s'
