URLTED = 'http://www.ted.com'
URLPROFILES = URLTED + '/profiles'
URLFAVORITES = URLPROFILES + '/favorites/id/'
URLADDREMFAV = URLPROFILES + '/%sfavorites'
URLSPEAKERS = URLTED + '/speakers?orderedby=TALKPOSTED&page=%s&alphabylastname=%s'
URLTHEMES = 'http://www.ted.com/themes'
URLRSS = 'http://feeds.feedburner.com/tedtalks_video'
